#+title: Recetas para la base de datos


* Recetas

** Mousse de chocolate :receta:

*** Nombre
Mousse de chocolate

*** Instrucciones
Hacer una rica mousse de chocolate

*** Observaciones
    Que te salga rica
*** Ingredientes

|-----------+-------|
| Yemas     | 5u    |
| Azúcar    | 70 gs |
| Agua      | 50gs  |
| Claras    | 5u    |
| Manteca   | 100gs |
| Chocolate | 250gs |


** Pan de papa para hamburguesas                                     :receta:
*** Nombre 
 Pan de papa para hamburguesas

***  Instrucciones
 Hervir y pisar la papa.  Mezclar todos los ingredientes menos la manteca hasta que estén integrados.  Dejar reposar 10 minutos.  Amasar mientras se agrega la manteca.  Bolear trozos de 120gs y colocar en moldes enmantecados.  Pincelar con huevo y leche en partes iguales.  Dejar levar hasta que doblen en tamaño.  Es importante no hornear antes de que hayan terminado de levar para que no rompan en el horno.  Hornear por 15 minutos en el horno a 180ºC y un recipiente con agua en el horno.  Volver a pincelar al sacarlos del horno.  Tip Mica Musre: Para conservar la humedad en caso de freezar es mejor meter los panes al freezer cuando todavía están calientes.

*** Observaciones
 El porcentaje de agua resulta en general bajo.  Usé 195gs y resultó demasiada hidratación, con una masa dificil de manejar.

*** Ingredientes
    
 |----------------+----------|
 | harina         | 500gs    |
 | agua           | 135gs    |
 | poolish        | 100gs    |
 | puré           | 120gs    |
 | huevo          | 55gs     |
 | manteca        | 30gs     |
 | azúcar         | 30gs     |
 | leche en polvo | 25gs     |
 | sal            | 10gs     |

